name: CI

on: [push]

jobs:
  iOS:
    name: Test iOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.5,name=iPhone 11 Pro"]
    steps:
      - name: Cache Carthage
        uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: sh -c 'cd image_server && php -S 0.0.0.0:9000 -c . >/dev/null &' && carthage update --platform iOS && set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "RestingKit.xcodeproj" -scheme "RestingKit" -destination "${{ matrix.destination }}" clean test | xcpretty